<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rkt</string>
	</array>
	<key>name</key>
	<string>Racket (soegaard)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>string datums  are enclosed in ". Inside a string \" is used to escape an ".</string>
			<key>match</key>
			<string>\"([^"])*\"</string>
			<key>name</key>
			<string>constant</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>booleans</string>
			<key>match</key>
			<string>((\#[tT])|(\#[fF])|(\#true)|(\#false))(?=[()\[\]{}",'`;\ \s])</string>
			<key>name</key>
			<string>constant</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>character datum</string>
			<key>match</key>
			<string>\#\\[A-Za-z]([A-Za-z])*</string>
			<key>name</key>
			<string>constant</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>general decimal number</string>
			<key>match</key>
